version: '3'
services:
  frontend:
    container_name: webapp
    build:
      context: . # relative to docker-compose command running directory (.) means this folder
      dockerfile: dockers/angular/Dockerfile # specify path to Dockerfile it starts on current folder application
    image: angular # repository
    # it's nice command So you are not needed to specify -p 8080:80
    ports:
      - '8080:80'
    stdin_open: true # stdin_open and tty: keep open the terminal after building container
    tty: true
