# docker compose with extends docker compose files
version: '3'
services:
  frontend:
    # can extends service that you need
    extends:
      file: docker-compose-angular.yml # specify file
      service: frontend  # specify service that you want to map, Remember you can use the same service name
# Step run
# 1. docker-compose up -d --build
